### ISSUE TITLE
WeekView: Events that don't overlap the current day aren't displayed

### ISSUE THREAD

**Issue by mileskrell** [Skyost/FlutterWeekView#1]
It appears that events in WeekView aren't displayed unless at least some part of the event occurs during the current day.

**To Reproduce**
1. Open the [example app](https://github.com/Skyost/FlutterWeekView/tree/master/example).
2. Add an event not during the current day. [Here's what I changed](https://gist.github.com/mileskrell/326de58ec49e1a79ae1c1073f36a2c63).
3. Run the app and scroll to the day of the event.
4. Observe that the event is not displayed.

**Expected behavior**
That all events occurring on the dates displayed by the WeekView will be displayed, regardless of whether they overlap the current date.

Thanks for making this library by the way! 🙂

**Comment by Skyost** [comment]
I'm sorry but that's the normal behavior 😕

If you want to show all your events then put them the same date as your `DayView` instance. If you want to show more than one day, then consider using `WeekView`.

**Comment by mileskrell** [comment]
I'm seeing this behavior with `WeekView`. (I haven't even tried `DayView` yet.)

**Comment by Skyost** [comment]
Then if you want to show your events you have two options :

* You change your events dates.
* You change your `WeekView` dates (in your example something like `dates: [date.add(Duration(days: 2))]` will work).

But as I said, not showing events which are not in the provided dates is the required behavior.

**Comment by mileskrell** [comment]
[I've added that to my `dates`](https://gist.github.com/mileskrell/326de58ec49e1a79ae1c1073f36a2c63#file-weekview_issue-patch-L13), but I'm still not seeing this event.

I think I might have misunderstand your initial response. Is only showing events that overlap the current day the intended behavior? (I understand that not showing events which are not in the provided dates is intended.)

**Comment by Skyost** [comment]
> Is only showing events that overlap the current day the intended behavior?

Yes. For example if you have let's say three dates : `2020-01-13`, `2020-01-14` and `2020-01-15`. If you have two events :

* **Start :** `2020-01-12 21:00` **End :** `2020-01-12 23:00`
* **Start :** `2020-01-15 23:00` **End :** `2020-01-16 02:00`

The first one will not appear at all in your `WeekView` while the second one will partially appear on the day `2020-01-15` (on the right of `2020-01-14`).

**Comment by mileskrell** [comment]
Just to check my understanding: if in your example, we imagine that the current day was `2020-01-13` or `2020-01-14`, then the expected behavior would be that neither of the two events would be visible, because neither overlaps the current day?

I'm unsure that I'm understanding this correctly, because in your comment, you stated that the second event **would** be visible. But as I understand it, that would only happen if the current day were `2020-01-15`.

Thanks for taking the time to explain this!

**Comment by Skyost** [comment]
Well, it doesn't depend on the current the day but on the dates your provide to the widget via the `dates` parameter. You're not limited to only one date, you can provide as many dates as you want.

In my example, you provide three dates `2020-01-13`, `2020-01-14` and `2020-01-15`. You open the widget and you see the events that are starting and / or ending on `2020-01-14`. So in this example you see nothing.    
**But** if you scroll on your right, you see the events that are starting and / or ending on `2020-01-15`. So you see the second event (as it's starting on `2020-01-15` at `23:00`). If you scroll on your left, you see nothing.

You can check the currently shown date here :

<img height="300" src="https://user-images.githubusercontent.com/3882599/72384833-864d9780-371e-11ea-9576-2ef6ea667ed5.png">

**Comment by mileskrell** [comment]
> it doesn't depend on the current the day but on the dates your provide to the widget via the `dates` parameter

Okay, it's good to hear that the widget isn't *supposed* to be affected by the current day. However, this isn't what I've experienced. For some reason, I'm only able to see events that occur during the current day.

For example, with the following code…
```dart
WeekView(
      dates: [DateTime(2020, 1, 14), DateTime(2020, 1, 15), DateTime(2020, 1, 16)],
      events: [
        FlutterWeekViewEvent(
          title: 'Event on 2020-01-14',
          description: 'Description',
          start: DateTime(2020, 1, 14, 12),
          end: DateTime(2020, 1, 14, 13),
        ),
        FlutterWeekViewEvent(
          title: 'Event on 2020-01-15',
          description: 'Description',
          start: DateTime(2020, 1, 15, 12),
          end: DateTime(2020, 1, 15, 13),
        ),
        FlutterWeekViewEvent(
          title: 'Event on 2020-01-16',
          description: 'Description',
          start: DateTime(2020, 1, 16, 12),
          end: DateTime(2020, 1, 16, 13),
        ),
      ],
    );
```
…I see this:
![missing_events](https://user-images.githubusercontent.com/16272279/72443588-81b7cc00-377c-11ea-99e5-020c1663ac6f.gif)
Any idea as to why this is happening?

**Comment by Skyost** [comment]
Wow, you're right, that's not normal. I'm gonna check it soon.

**Comment by Skyost** [comment]
So you were right ! Sorry for my bad understanding, I'm not a native english speaker 😅

**Comment by mileskrell** [comment]
All good! "Current day" *was* kind of ambiguous here; I probably should have just included a screen recording to begin with. Thanks again for the library, as well as for the quick fix!

**Comment by Skyost** [comment]
No problem, thanks for reporting !
