### ISSUE TITLE
Only show title of event in WeekView cell

### ISSUE THREAD

**Issue by farrukhnajmi** [Skyost/FlutterWeekView#105]
**Is your feature request related to a problem? Please describe.**
My use case requires only showing the title in a WeekView cell. Is this possible?

**Describe the solution you'd like**
My use case requires only showing the title in a WeekView cell. Is this possible?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Skyost** [comment]
Use `eventTextBuilder` (see https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/event.dart#L81).
