### ISSUE TITLE
Click detection in an event

### ISSUE THREAD

**Issue by MarlonPra** [Skyost/FlutterWeekView#106]
Hello, I want to know what should I use to detect the click or tap to an event so that it can execute a window or something, thank you very much.

![image](https://github.com/Skyost/FlutterWeekView/assets/79668146/999ceb9d-8f3c-46c9-b1cc-cde6f8281a01)

**Comment by Skyost** [comment]
`onTap` parameter (of `FlutterWeekViewEvent`) is the way.

**Comment by MarlonPra** [comment]
> `onTap` parameter (of `FlutterWeekViewEvent`) is the way.

Could you give me an example of how to use it?

**Comment by Skyost** [comment]
You can check my project _Unicaen Timetable_, on Github :

https://github.com/Skyost/UnicaenTimetable/blob/master/lib/widgets/flutter_week_view.dart#L43

**Comment by MarlonPra** [comment]
> You can check my project _Unicaen Timetable_, on Github :
> 
> https://github.com/Skyost/UnicaenTimetable/blob/master/lib/widgets/flutter_week_view.dart#L43

Thank you very much, I would like to know if you have discord or something similar, I am making a schedule for my University and I have some questions about the calendar, thank you very much 😁
