### ISSUE TITLE
Events not displayed dynamically in DayView

### ISSUE THREAD

**Issue by mamirix** [Skyost/FlutterWeekView#11]
**Describe the bug**
I put my events in an array of FlutterWeekViewEvent. it's not displayed(painted) unless I purposely throw and exception that cause the whole page to be repainted not only the DayView 

**To Reproduce**
this is the code I used to put events into day view:

List<FlutterWeekViewEvent> _listEvents = List<FlutterWeekViewEvent>();
    try {
      _lst?.forEach((e) {
        _listEvents.add(
          FlutterWeekViewEvent(
            title: e.service?.productName ?? "No Product Name",
            description: e.service?.productDescription ?? 'No description',
            start: e.start,
            end: e.start.add(Duration(hours: 1)),
          ),
        );
      });
    } catch (e) {
      print('processing event error $e');
    }

    return DayView(
      eventsColumnBackgroundPainter: _bkgpntr,
      date: _day,
      events: _listEvents,
      currentTimeCircleColor: Colors.pink,
    );
  }

**Desktop (please complete the following information):**
using chrome Browser

**Additional context**
The Dayview bar and current timeline are displayed correctly. only the events are not displayed

**Comment by mamirix** [comment]
I solved the problem.
I wrapped DayView in a container and provided a key to the container.

**Comment by Skyost** [comment]
That's fine if you've solved your problem.
