### ISSUE TITLE
Timescala doesn't zoom with content

### ISSUE THREAD

**Issue by kuemme01** [Skyost/FlutterWeekView#12]
**Describe the bug**
When zooming on DayView, the time scala on the left side doesn't scoll too

**To Reproduce**
1. Build DayView
2. Try to zoom

**Expected behavior**
Timescala should zoom the same way then content.

**Tablet:**
 - OS: Android
 - Version 9

**Comment by Skyost** [comment]
Can you post your code please ? Because I don't have any problem :
![untitled](https://user-images.githubusercontent.com/3882599/74650026-1600be80-5181-11ea-8ce8-25f55ccfdf68.gif)

**Comment by kuemme01** [comment]
I just used your example code inside of an Scaffold and have the same behavior on Android 9 and iOS13.

**Comment by Skyost** [comment]
Can you please try to run the sample app (in the `example` folder) and see if it works ?

**Comment by Skyost** [comment]
Just reproduced your bug. I'm working on a fix.
