### ISSUE TITLE
Need tap gesture on tap of time slot

### ISSUE THREAD

**Issue by manishvill** [Skyost/FlutterWeekView#19]
**Is your feature request related to a problem? Please describe.**
When user want to add event, user always have to select date and time, it will be good to have gesture detector on time slot and hight light the same slot on tap on basis of bool and color.

**Describe the solution you'd like**
 when user tap inside 1 hr - 2hrs box it will call on tap method with start datetime as parameter 

**Describe alternatives you've considered**
No alternative

**Comment by BuddyShen** [comment]
Tap event goes wrong randomly in DayView while clicking on a same event.

**Comment by BuddyShen** [comment]
sometimes it jumps to other event automatically if clicking on same event

**Comment by BuddyShen** [comment]
onTap & onLongPress has same issue

**Comment by Skyost** [comment]
@BuddyShen What does this have to do with this issue ?

**Comment by BuddyShen** [comment]
> @BuddyShen What does this have to do with this issue ?

Just add ontap & onlongpress (with print output) on each event and you will see the reaction of each event will jump randomly in-between each event.

**Comment by BuddyShen** [comment]
> @BuddyShen What does this have to do with this issue ?

It will be used to modify or delete certain event(a) through ontap or onlongpress

**Comment by BuddyShen** [comment]
> @BuddyShen What does this have to do with this issue ?


It will be used to modify or delete certain event(s) through ontap or onlongpress

**Comment by tegarkurniawan** [comment]
same request this feature

**Comment by tegarkurniawan** [comment]
Apparently there is this feature, Thanks

FlutterWeekViewEvent(
          onTap: (){
            Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (_) => ViewEvent(
                                        event: _newsList[i],
                                      )));
          },
          title: _newsList[i].name,
          start: date.add(Duration(
              hours: _newsList[i].startHour,
              minutes: _newsList[i].startMinute)),
          end: date.add(Duration(
              hours: _newsList[i].endHour, minutes: _newsList[i].endMinute)),
          description: _newsList[i].description,
        )
