### ISSUE TITLE
This title of event won't show when the event's duration is short. 

### ISSUE THREAD

**Issue by leungvanice** [Skyost/FlutterWeekView#21]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Skyost** [comment]
Please fill the template fields.

**Comment by leungvanice** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-25 at 18 03 02](https://user-images.githubusercontent.com/52531084/77531203-852ea880-6ecd-11ea-8511-380c3c817533.png)

**Comment by leungvanice** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-25 at 19 20 12](https://user-images.githubusercontent.com/52531084/77531314-adb6a280-6ecd-11ea-83ae-4b9ee3493445.png)

**Comment by Skyost** [comment]
The template is still not filled. And tell me, how would you like to display an event title with so little space ? You're free to change [the default behavior](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/event.dart#L43) tho.

**Comment by leungvanice** [comment]
I am running on an iOS simulator. But I don't know how to find the iOS version.  
The duration of first and second event are 3 minutes and 10 minutes. 
It will show the title when the event is not too short. 
And I have fill in the data. 
`events:
                          snapshot.data.documents.map((DocumentSnapshot doc) {
                        return FlutterWeekViewEvent(
                          backgroundColor:
                              colorFromString(doc['belongedTask']['colorHex']),
                          title: doc['belongedTask']['title'],
                          description: doc['note'] != '' ? doc['note'] : '',
                          start: doc['startTime'].toDate(),
                          end: doc['endTime'].toDate(),
                        );
                      }).toList(),`

**Comment by Skyost** [comment]
> It will show the title when the event is not too short.

It actually does :wink:
