### ISSUE TITLE
Limit hours in a day

### ISSUE THREAD

**Issue by uitlegentekst** [Skyost/FlutterWeekView#24]
Hi Skyost,

Great widget, that you have made!

I'm trying to implement it to plan business days. It would be great if it's possible to limit the hours in a day, e.g. from 9.00 to 17.00. That would make the schedule more concise. 

Implementation could be as a start/end paramater. eg:
dayStartHour: double
dayEndHour: double

Another implementation could be to limit the hours to the times in which there are actually events... so to trim off the empty hours at the beginning and end of the day schedule. Eg:
trimEmptyHours: bool

Well, either way, thanks for your widget!

Mark

**Comment by Skyost** [comment]
Love this idea !
