### ISSUE TITLE
inital hour not doing anything

### ISSUE THREAD

**Issue by TacoAndPie** [Skyost/FlutterWeekView#25]
both initial hour and initial minute do nothing
also it would be great to have final hour + final minute
thanks!

**Comment by Skyost** [comment]
> both initial hour and initial minute do nothing

Which widget are you using ? What is your code ? Also if `scrollToCurrentTime` is enabled the widget may scroll to current time without scrolling to the provided initial hour & minute (if you are on the current day).

> also it would be great to have final hour + final minute

See #24.

**Comment by Skyost** [comment]
Closed due to inactivity.
