### ISSUE TITLE
Format Date Header and Format AM/PM on hours list 

### ISSUE THREAD

**Issue by thegenet** [Skyost/FlutterWeekView#28]
Awesome plugin  but it will be nice if we could use customs formats on the date in the header section and hours to be more human readable use the AM/PM

**Comment by Skyost** [comment]
See [date formatter](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/style.dart#L14) and [time formatter](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/style.dart#L17).

**Comment by thegenet** [comment]
Great man, I search the docs and didn't found how to format the dates and hours maybe you should add an example so you won't be bother again for something this simple 😂

**Comment by Skyost** [comment]
Yes, it was listed in [Common options](https://github.com/Skyost/FlutterWeekView/tree/81fef60cca3d00d7000e3d428871acafc8b15448#common-options) paragraph on README but I removed it when I've added the `Style` class. Maybe I should list styling options yeah.
