### ISSUE TITLE
ADD ability to set custom subhour lines #UX

### ISSUE THREAD

**Issue by allanlaal** [Skyost/FlutterWeekView#3]
## use case 

In addition to the main gray *:00 hour lines, want to have a bit more faded lines showing at *:30 and maybe even lines with different styles shown at *:15 and *:45

**Comment by allanlaal** [comment]
and why not have support for having custom lines for defined hours

## use case:

a thicker line at 09:00, 12:00, 15:00, 18:00 to denote long pomodoro breaks

**Comment by Skyost** [comment]
I think I'm gonna implement this by creating a `Background` class. The idea would be to replace the current system by a canvas.

This would allow everyone to easily override the class and draw whatever they want.
