### ISSUE TITLE
WeekView.builder crashes when dateCount is null

### ISSUE THREAD

**Issue by luistrivelatto** [Skyost/FlutterWeekView#32]
**Describe the bug**
When using the WeekView.builder constructor, a dateCreator is required, but not a dateCount (which is in accordance to idiomatic builder constructors in Flutter). Indeed, the constructor allows that, with the assertion `assert(dateCount == null || dateCount >= 0)`. However this causes a crash when `dateCount == null` and a WeekViewController isn't passed, since a WeekViewController is then instanced using dateCount, but WeekViewController itself doesn't allow for a null dateCount: `assert(dayViewsCount != null && dayViewsCount > 0)`.

**To Reproduce**
1. Take the example code on the package.
2. Replace `_DemoWeekView` with
```dart
class _DemoWeekView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WeekView.builder(
      dateCreator: (index) => DateTime(2020, 1, 1 + index),
      events: [],
    );
  }
}
```
3. Run the app and click on the Demo week view button. This should show the following error:
```
'package:flutter_week_view/src/controller.dart': Failed assertion: line 160 pos 16: 'dayViewsCount != null && dayViewsCount > 0': is not true.
```

**Expected behavior**
No errors should be thrown, and the controllers should be managed seamlessly until `dateCreator` returns null for a given index.

**Smartphone (please complete the following information):**
 - Device: Galaxy A8
 - OS: Android 9

**Comment by Skyost** [comment]
Thanks for pointing this out. The problem is that internally, the `WeekViewController` is instantiating a `DayViewController` for each `DayView`. This allows to scale them at the same time, to scroll them, etc...

**Comment by luistrivelatto** [comment]
The fix looks great, congrats :)
