### ISSUE TITLE
Week view event that spans over multiple days is rendered incorrectly

### ISSUE THREAD

**Issue by luistrivelatto** [Skyost/FlutterWeekView#42]
**Describe the bug**
A week view event that spans over multiple days is only shown in the days of the start and end date of the event.

**To Reproduce**
1. Create the following week view widget:
```dart
      WeekView(
        dates: [DateTime(2020, 1, 1), DateTime(2020, 1, 2), DateTime(2020, 1, 3)],
        style: const WeekViewStyle(
          hourRowHeight: 30.0,
          dayViewWidth: 90.0,
        ),
        events: [
          FlutterWeekViewEvent(
            title: 'An event 1',
            description: 'A description 1',
            start: DateTime(2020, 1, 1, 20),
            end: DateTime(2020, 1, 3, 6),
          ),
        ],
      ),
```
2. Check the widget's UI to see that it is not rendered on 2020-01-02.

**Expected behavior**
There should be an event box covering the full day of 2020-01-02.

**Screenshots**
![week_view_multi_day_event](https://user-images.githubusercontent.com/21317528/86507718-d2fe5b00-bdb0-11ea-8e7e-75f67fbc4fb2.png)

**Smartphone (please complete the following information):**
Device: Galaxy A8
OS: Android 9

**Comment by Skyost** [comment]
Thanks for reporting ! As I said on #41, I have not the time to work on it before (at least) the next wednesday.
