### ISSUE TITLE
Add decoration property in HourColumn

### ISSUE THREAD

**Issue by caiogranero** [Skyost/FlutterWeekView#48]
Hi again :)

It will be a nice option if we can add a decoration optional property in HourColumn widget to set the Container decoration instead of simply change the color.

I made a fork with what i was thinking of implementation.

https://github.com/caiogranero/FlutterWeekView

What do you think?

**Comment by Skyost** [comment]
Done in cb73c6cc7e8489194547dc764f554c2ae469b924. But thanks a lot for your fork !
