### ISSUE TITLE
ADD background events support

### ISSUE THREAD

**Issue by allanlaal** [Skyost/FlutterWeekView#5]
some Events can be marked as background:
 
 * event width can be set in % (see use cases below)
 * showing event start-end times and/or title and/or description can be set to hidden
 * background events will be always shown as the lowest in the stack and will not be detected for collisions with upper tier events
 * tapping on background events will not trigger anything, they are just background coloring

## use case: generating a sunrise-sunset background

this feature can be used to generate a background for each day that shows the location of the sun in the sky using the events width (sun intensity is useful in some regions to plan out ones day). the app using this can generate these by making lots of 15..60min events with different widths

## use case: timeboxes

this feature can be used to color different parts of the day with different color to denote timebox/timebudget/timeblock preference for the user. this also should not collide with real events

## use case: weather

the amount of rain can also be shown the same way as sun position

**Comment by Skyost** [comment]
Well, I think everything here can be done using a custom `EventsColumnBackgroundPainter` (added in a2dcadb5c4db92152f1a9777f6f1d79ceaa07f50 to fix #3).
