### ISSUE TITLE
Be able to create custom horizontal rule and time inidicator with builders

### ISSUE THREAD

**Issue by Dekhnar** [Skyost/FlutterWeekView#51]
I'm trying to customize the horizontal hour displayed in the left and the indicator. I want to be able to give my own Widget builder as parameters for creating specific createCurrentTimeRule and createCurrentTimeCircle to match my specific UI.

Is there a way to do this ?

**Comment by Dekhnar** [comment]
I think you can expose a `final DayViewBuilders builders;` as parameter, if builders are provided you use them.
`typedef Builder = Widget Function(BuildContext context);`
```
class DayViewBuilders {

  final Builder hourBuilder;
  final Builder todayHourBuilder;

  final Builder indicatorBuilder;
}
```

**Comment by Dekhnar** [comment]
Exactly what i need thanks @Skyost.

**Comment by Skyost** [comment]
@Dekhnar No problem, feel free to test it and report me any bug you encounter :wink:
