### ISSUE TITLE
Detect on day changed in WeekView

### ISSUE THREAD

**Issue by caiogranero** [Skyost/FlutterWeekView#52]
I don't know if this alread exists, but would be helpfull if we have a `onDayChanged` or `onVisibleDayChanged`, something like this to make callback actions when user change the current day on week view by swiping action.

**Comment by Skyost** [comment]
It's not possible to add such callbacks because the day view width is configurable. Therefore, you can have multiple day views shown on the screen (see screenshot [here](https://github.com/Skyost/FlutterWeekView/blob/master/test/golden/goldens/week_view_multi_day_event.png)).

**Comment by caiogranero** [comment]
Huum, thats works for me. Thank you :)
