### ISSUE TITLE
Add builder for HourColumn item

### ISSUE THREAD

**Issue by Dekhnar** [Skyost/FlutterWeekView#53]
Hi,

I want to put a rounded red container on the nearest hour from the current time.
![hourColumns](https://user-images.githubusercontent.com/59254555/90137905-8ece8500-dd76-11ea-835b-844820eeed6a.png)

Can you provide us a builder here:
https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/widgets/hours_column.dart#L60

to achieve it, it would be great :).

Best Regards.

**Comment by Dekhnar** [comment]
@Skyost any news for this?

**Comment by Skyost** [comment]
@Dekhnar I haven't started to work on this but feel free to submit your pull requests :wink:
