### ISSUE TITLE
12HR FORMAT

### ISSUE THREAD

**Issue by Arivuselvan5700** [Skyost/FlutterWeekView#56]
need to do more parsing to fit 12 hr format .

**Comment by Skyost** [comment]
What ?

**Comment by Arivuselvan5700** [comment]
We cant view 12hr timeformat .It would be so good if we have 12 hr format
for day view .
We wish you to implement on next update
Thanks .

**Comment by Skyost** [comment]
Just use the [`timeFormatter`](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/styles/hours_column.dart#L30) parameter.

**Comment by Arivuselvan5700** [comment]
thanks...I m new to flutter,
i am using flutterWeekView .
I need to edit the header where the date is showing ... is it possible to
have it in a container?

**Comment by Skyost** [comment]
No but you can always customize the parameters available in [this class](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/styles/day_bar.dart).
