### ISSUE TITLE
Is it possible to change the width of WeekView then rebuild the widget?

### ISSUE THREAD

**Issue by nadhirfr** [Skyost/FlutterWeekView#58]
**Is your feature request related to a problem? Please describe.**
I want to add a button to change the width of the dayview in WeekView class. I found out that dayViewWidth property in WeekViewStyle is final, which I could not change once it initialized.

Is there any advice about this one?

Thanks

**Comment by Skyost** [comment]
You could always try to put the week view in a stateful widget and change the width via `setState`.

**Comment by nadhirfr** [comment]
Hello @Skyost ,

I tried to put the week view in a stateful widget. Then change the weekViewStyle attribute via setState. However only dayViewSeparatorWidth and headerSize are changed, the widget rebuild, but dayViewWidth doesn't change.

![Android-Emulator-Pixel-2-API-30](https://user-images.githubusercontent.com/16182814/92455265-ab31d600-f1eb-11ea-8f9f-1e97069b000a.gif)

**Comment by Skyost** [comment]
Oh I see. I may need to check `didChangeDependencies` in the week view.

**Comment by Skyost** [comment]
I fixed it in 741acc128950fdb6975c4e0c1ce188168ba9af32 (I hope), could you please tell me if it works for you ? You can try the changes using :

```yaml
dependencies:
  flutter_week_view:
    git:
      url: https://github.com/Skyost/FlutterWeekView
      ref: master
```

(in your `pubspec.yml`)

**Comment by nadhirfr** [comment]
Hi @Skyost checked and got following result:
![Android-Emulator-Pixel-2-API-30 14-09-20 2](https://user-images.githubusercontent.com/16182814/93041420-b1ee9c00-f676-11ea-99ef-cda3eeb6a152.gif)

I think the width of the event changed, but not with the Day View width. And the scrolling is back to the first day

**Comment by Skyost** [comment]
Thanks for checking out @nadhirfr. I think I still have to call a `setState` somewhere...

**Comment by Skyost** [comment]
I think it should be fixed now. Could you try it by running `pub upgrade` @nadhirfr ?

**Comment by lukiinhas1616** [comment]
Skyost, tudo bem?
Existe alguma forma de aumentar o zoom, o Height do evento ou criar intervalos de 30minutos ao invés de 1 hora, de forma estática, de maneira que possa ser visualizado o conteúdo de eventos pequenos?
