### ISSUE TITLE
Is it possible to use DayView without a DayBar?

### ISSUE THREAD

**Issue by martingutsche** [Skyost/FlutterWeekView#60]
**Is your feature request related to a problem? Please describe.**
As far as I know it is currently not possible to use DayView without a DayBar. I have an application where the date is already shown as part of the AppBar, so I don't need a DayBar.

**Describe the solution you'd like**
For this reason I'd like DayViews constructor to accept an argument that results in DayView not beeing built.

**Describe alternatives you've considered**
I've looked through the constructors of DayView and DayBarStyle but didn't find anything that could accomplish what I need. In case I've missed something, I would be very grateful if you could provide an alternative way to accomplish this.

**Comment by Skyost** [comment]
Try by passing `headerSize: 0` to either `DayViewStyle` or `WeekViewStyle` constructor.

**Comment by martingutsche** [comment]
@Skyost That works for me, thank you :1st_place_medal:
