### ISSUE TITLE
RenderBox error in FlutterWeekViewEvent in DayView

### ISSUE THREAD

**Issue by VietThang-Antoree** [Skyost/FlutterWeekView#64]
RenderBox Error when rebuild/closing the screen which contains the DayView Widget.

I have 2 screens. When I navigate to the screen which contains the DayView Widget, it works fine. But whenever I do a hot reload, or navigate to another screen, the following Exception is thrown and the screen turns black, not interactive.

The bug only happens when I add a FlutterWeekViewEvent in the event list in DayView Widget

`RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout().
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1792 pos 13: 'debugDoingThisResize || debugDoingThisLayout ||
              (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)'
`

The version I am at is 1.0.0+2

**Comment by VietThang-Antoree** [comment]
May I ask you what is the purpose of the reset() function called in didUpdateWidget in the DayView Widget? I commented the line and things just work.
`

@override
  void didUpdateWidget(DayView oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.date != widget.date) {
      scheduleScrollToInitialTime();
    }

    // reset();
    createEventsDrawProperties();
  }

`

**Comment by Skyost** [comment]
Thanks for your report and your suggestion. Would it be possible to get the full stacktrace ? If you want to wait, you can downgrade to `1.0.0+1`.

**Comment by Skyost** [comment]
Closed due to inactivity.
