### ISSUE TITLE
How to use the dayBarStyleBuilder

### ISSUE THREAD

**Issue by scshivam** [Skyost/FlutterWeekView#75]
Please provide some example code to use the dayBarStyleBuilder.

**Comment by Skyost** [comment]
Yep. First, you have to understand that `DayBarStyleBuilder` is a function that accepts a `DateTime` and returns a `DayBarStyle` (see [here](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/widgets/week_view.dart#L24)). [Here](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/utils/builders.dart#L134)'s a such function.

So if you want to use it as an argument, just write something like this :

```dart
dayBarStyleBuilder: (date) {
  // Get whatever info you want about this date...
  return const DayBarStyle();
}
```
