### ISSUE TITLE
Show multiple days on screen

### ISSUE THREAD

**Issue by yanis60** [Skyost/FlutterWeekView#77]
Hi,
How to show multiple days on the screen at the same time?

**Comment by Skyost** [comment]
In the WeekView style, set `dayViewWidth: <what you want>` (I use it [here](https://github.com/Skyost/UnicaenTimetable/blob/master/lib/pages/week_view/week_view.dart#L63) to fit more than one DayView for large screens).

**Comment by yanis60** [comment]
merci beaucoup.

How to change date format to dd MMM yyyy?

**Comment by Skyost** [comment]
In the day bar ? Just pass a custom `dateFormatter` to the day bar style :wink:

**Comment by yanis60** [comment]
could you please show me an example?

**Comment by Skyost** [comment]
```dart
style: DayBarStyle(
  dateFormatter: (date) => DateFormat.yMMMd().format(date)
)
```

(assuming that you're using [`intl`](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html)).

**Comment by yanis60** [comment]
merci beaucoup mon frère
