### ISSUE TITLE
Navigating throught date programmatically

### ISSUE THREAD

**Issue by yanis60** [Skyost/FlutterWeekView#79]
Hi,
How to navigate throught date programmatically in weekview?

**Comment by Skyost** [comment]
Hi,
It's not possible currently. Being able to use a custom [horizontal scroll controller](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/widgets/week_view.dart#L144) would make this possible.

**Comment by hmarat** [comment]
@yanis60 did you solve this problem?

**Comment by yanis60** [comment]
@hmarat no :(

**Comment by hmarat** [comment]
@yanis60 By the way, can you control and fire some callback when date changes with scrolling?

**Comment by hmarat** [comment]
@yanis60 you can make your ListView.builder, where every item is DayView widget
