### ISSUE TITLE
Add Ripple effect (using InkWell) to the events

### ISSUE THREAD

**Issue by dJani97** [Skyost/FlutterWeekView#88]
**Describe the problem**

When the user taps on an event, there is no visual feedback. I would suggest adding a ripple effect, as it's used on most clickable surfaces in Material Design.

**A possible solution**

Wrapping the event widgets with an `InkWell` instead of the currently used `GestureDetector` would probably solve this.

Here is the visual difference between the two: [Visual Difference](https://stackoverflow.com/a/68090057/5521187)

**Comment by rodrigosa7** [comment]
#101 

Just created a pull request for this issue.
