### ISSUE TITLE
not responsive

### ISSUE THREAD

**Issue by pramod51** [Skyost/FlutterWeekView#94]
UI is not responsive....when we change screen width, then event width should be changed

**Comment by Skyost** [comment]
You have to adapt the [`dayViewWidth`](https://github.com/Skyost/FlutterWeekView/blob/master/lib/src/styles/week_view.dart#L9) according to device screen width.

**Comment by pramod51** [comment]
thank you sir, is it possible to add separator at 30min positions??

**Comment by Skyost** [comment]
Not now, sorry.
